name: API - Stress Tests

on:
  workflow_run:
    workflows: ['API - CI']
    types: 
      - completed
  schedule:
    - cron: '35 13 * * *' 

jobs:
  stress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo 'TESTE STRESS RODANDO'